<style type="text/css" title="Bright Colours">
th {font-family: Arial; font-size: 10pt;}
td {font-family: Courier; font-size: 12pt;}
h4 {color: blue; font-size: 14pt;}
p.greentext {color: green;}
.c {
border: 1px solid #333; /* Рамка */
display: inline-block;
padding: 5px 15px; /* Поля */
text-decoration: none; /* Убираем подчёркивание */
color: #000; /* Цвет текста */
align:"center";
}
.c:hover {
box-shadow: 0 0 5px rgba(0,0,0,0.3); /* Тень */
background: linear-gradient(to bottom,white, white); /* Градиент */
color: #a00;
align:"center";
}
</style>
</head>
<body>